accounts/urls.py
from django.contrib.auth import views as django_views
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', django_views.LoginView.as_view(), name='login'),
    path('logout/', django_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

chat/urls.py
from django.urls import path

from .views import Index, RoomView, StartChat, VideoChat

app_name = 'chat'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('<str:room_name>/', RoomView.as_view(), name='room'),
    path('start/<str:username>/', StartChat.as_view(), name='start'),
    path('video/<str:room_name>/', VideoChat.as_view(), name='video'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('accounts.urls')),
    path("", include("chat.urls")),

]

accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager


class User(AbstractUser):
    objects = UserManager()

chat/models.py
import uuid

from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Room(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='first_user')
    second_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='second_user')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_user.username + ' ' + self.second_user.username


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, related_name="messages", on_delete=models.CASCADE)
    text_content = models.CharField(max_length=255)
    # file_content = models.FileField(upload_to='files/', blank=True, null=True)
    # image_content = models.ImageField(upload_to='images/', blank=True, null=True)
    image_content = models.TextField(blank=True, null=True)
    audio_content = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + self.room.first_user.username + self.room.second_user.username

    def get_short_date(self):
        return self.created_at.strftime("%H:%M")

    def get_img_tag(self):
        if self.image_content:
            return f'<img src="{self.image_content}" width="150" height="150">'
        else:
            pass

    def get_audio_tag(self):
        if self.audio_content:
            return f'<audio controls controlslist="nodownload"><source src="{self.audio_content}" type="audio/ogg"></audio>'
        else:
            pass
       

accounts/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect


from .forms import UserCreationForm


def signup(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(request, user)
        return redirect('chat:index')
    return render(request, 'registration/signup.html', {'form': form})

chat/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from .models import Room

User = get_user_model()


class Index(View):
    def get(self, request):
        q = self.request.GET.get('q', '')
        if self.request.user.is_authenticated:
            if q:
                users = User.objects.exclude(id=self.request.user.id).filter(username__icontains=q)
            else:
                users = User.objects.exclude(id=self.request.user.id)
        else:
            users = []

        context = {
            'users': users
        }
        return render(self.request, 'index.html', context)


class RoomView(LoginRequiredMixin, View):

    def get(self, request, room_name):
        room = Room.objects.filter(id=room_name).first()

        if (self.request.user == room.first_user) or (
                self.request.user == room.second_user):
            messages = room.messages.all()
            context = {
                'room': room,
                'messages': messages
            }
            return render(self.request, 'chat/room.html', context)
        return redirect('chat:index')


class StartChat(LoginRequiredMixin, View):
    """
    take username and start chat with request user and him/her
    """

    def get(self, request, username):
        second_user = User.objects.get(username=username)
        room = Room.objects.filter(
            first_user=self.request.user,
            second_user=second_user).first() or Room.objects.filter(
            second_user=self.request.user, first_user=second_user).first()
        if room:
            return redirect('chat:room', room_name=room.id)
        else:
            room, _ = Room.objects.get_or_create(first_user=self.request.user, second_user=second_user)
        return redirect('chat:room', room_name=room.id)


class VideoChat(LoginRequiredMixin, View):

    def get(self, request, room_name):
        room = Room.objects.filter(id=room_name).first()
        if (self.request.user == room.first_user) or (self.request.user == room.second_user):
            context = {
                'room': room
            }
            return render(self.request, 'chat/video_chat.html', context)
        return redirect('chat:index')

templates/chat/room.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
    <div class="col-sm-8 conversation">
        <div class="row heading">
            <div class="col-sm-2 col-md-1 col-xs-3 heading-avatar">
                <div class="heading-avatar-icon">
                    <img src="https://bootdey.com/img/Content/avatar/avatar6.png">
                </div>
            </div>
            <div class="col-sm-8 col-xs-7 heading-name">
                <a class="heading-name-meta">
                    {% if room.first_user == request.user %}
                        {{ room.second_user }}
                    {% else %}
                        {{ room.first_user }}
                    {% endif %}</a>
                <span class="heading-online">Online</span>
            </div>
            <div class=" heading-dot">
                <div class="w-50">
                    <a href="{% url "chat:video" room.id %}">
                        <i class="fa fa-video fa-2x  pull-right " aria-hidden="true"></i>
                    </a>
                </div>
                <div class="w-50">
                    <i class="fa fa-phone-alt fa-2x  pull-right d-inline-block" aria-hidden="true"></i>
                </div>
            </div>
        </div>

        <div class="row message" id="conversation">
            {#            <div class="row message-previous">#}
            {#                <div class="col-sm-12 previous">#}
            {#                    <a>#}
            {#                        Show Previous Message!#}
            {#                    </a>#}
            {#                </div>#}
            {#            </div>#}
            {% for message in messages %}

                <div class="row message-body">
                    <div class="col-sm-12 message-main-{% if message.user == request.user %}sender{% else %}receiver{% endif %}">
                        <div class="{% if message.user == request.user %}sender{% else %}receiver{% endif %}">
                            <div class="media">
                                {% if message.image_content %}
                                    {{ message.get_img_tag|safe }}
                                {% endif %}
                                {% if message.audio_content %}
                                    {{ message.get_audio_tag|safe }}
                                {% endif %}
                            </div>

                            <div class="message-text">
                                {{ message.text_content }}
                            </div>
                            <span class="message-time pull-right">{{ message.get_short_date }}</span>
                        </div>
                    </div>
                </div>

            {% empty %}
                <div class="text-muted text-center">
                    No messages yet!
                </div>
            {% endfor %}
        </div>

        <div class="row reply">
            <div class="col-sm-1 col-xs-1 reply-emojis">
                <input type="file" name="file" id="file" class="hide" style="position: absolute">
                <label for="file" class="btn"><i class="fas fa-paperclip fa-2x"></i></label>
            </div>
            <div class="col-sm-9 col-xs-9 reply-main">
                <input type="text" id="chat-message-input" class="form-control"
                       placeholder="Enter text here...">
            </div>
            <div class="col-sm-1 col-xs-1 reply-recording">
                <button><i class="fa fa-microphone" id="microphone" aria-hidden="true"></i></button>
            </div>
            <div class="col-sm-1 col-xs-1 reply-send">
                <button id="chat-message-submit"><i class="fa fa-paper-plane"></i></button>
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

templates/chat/video_chat.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}
    <div id="conversation" class="col-sm-8">
        <div class="row video-chat">
            <div class="col-md-6 bg-dark border">
                <video id="video-me"  width="250" height="250" src="">

                </video>
            </div>
            <div class="col-md-6">
                <video id="video-partner" width="250" height="250" src="" >

                </video>
            </div>
        </div>
        <div class="row video-buttons bg-dark text-center">
            <button id="video-chat-microphone" class="btn btn-primary"><i class="fa fa-microphone"></i></button>
            <button id="video-chat-camera" class="btn btn-primary"><i class="fa fa-camera"></i></button>
            <a href="{% url 'chat:room' room.id %}" class="btn btn-danger"><i class="fa fa-phone"></i></a>
        </div>
    </div>
{% endblock %}
{% block js %}
    {{ room.id|json_script:"room_id" }}
    {{ request.user.username|json_script:"first_user" }}
    {% if request.user == room.first_user %}
        {{ room.second_user.username|json_script:"second_user" }}
    {% else %}
        {{ room.first_user.username|json_script:"second_user" }}
    {% endif %}
    <script src="https://unpkg.com/peerjs@1.3.1/dist/peerjs.min.js"></script>
    <script src="{% static 'js/video_chat.js' %}"></script>
{% endblock %}

templates/index.html
{% extends 'layout/base.html' %}
{% block content %}


{% endblock %}

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
    {% include 'layout/cdn.html' %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'icons/favicon.ico' %}" type="image/x-icon">
</head>
<body>

<div class="container app">
    <div class="row app-one">
        <div class="col-sm-4 side">
            <div class="side-one">
                <div class="row heading">
                    <div class="col-sm-3 col-xs-3 heading-avatar">
                        <div class="heading-avatar-icon">
                            <div class="h4">Django_Chat</div>
                        </div>
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="col-sm-2 col-xs-2 heading-compose  pull-right">
                            <a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out-alt fa-2x  pull-right"
                                                                     aria-hidden="true"></i></a>
                        </div>
                    {% else %}
                        <div class="col-sm-2 col-xs-2 heading-compose  pull-right">
                            <a href="{% url 'accounts:login' %}"><i class="fa fa-sign-in-alt fa-2x  pull-right"
                                                                    aria-hidden="true"></i></a>
                        </div>
                        <div class="col-sm-2 col-xs-2 heading-compose  pull-right">
                            <a href="{% url 'accounts:signup' %}"><i class="fa fa-user-plus fa-2x  pull-right"
                                                                     aria-hidden="true"></i></a>
                        </div>
                    {% endif %}

                </div>
                {% if request.user.is_authenticated %}
                    <div class="row searchBox">
                        <div class="col-sm-12 searchBox-inner">
                            <div class="form-group has-feedback">
                                <form action="" method="get">
                                    <input id="searchText" type="text" class="form-control" name="q"
                                           placeholder="Search">
                                    <span class="glyphicon glyphicon-search form-control-feedback"></span>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endif %}

                <div class="row sideBar">
                    {% for user in users %}
                        <div class="row ">
                            <div class="col-sm-3 col-xs-3 sideBar-avatar">
                                <div class="avatar-icon">
                                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png">
                                </div>
                            </div>
                            <div class="col-sm-9 col-xs-9 sideBar-main">
                                <div class="row">

                                    <a href="{% url 'chat:start' user.username %}">
                                        <div class="col-sm-8 col-xs-8 sideBar-name">
                                            <span class="name-meta">{{ user }}</span>
                                        </div>
                                    </a>
                                    <div class="col-sm-4 col-xs-4 pull-right sideBar-time">
                                        <span class="time-meta pull-right">18:18</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div class="row sideBar-body mt-5">
                            <div class="col-sm-9 col-xs-9 ">
                                <div class="row">
                                    <div class="col-8 text-center ps-4">
                                        <div class="h3 text-dark">
                                            {% if request.user.is_authenticated %}
                                                {% if request.GET.q %}
                                                    No users found
                                                {% else %}
                                                    <a href="{% url 'chat:index' %}" class="name-meta">
                                                        All Users
                                                    </a>
                                                {% endif %}

                                            {% else %}
                                                <span>Login or Signup to chat </span>
                                                <i class="ml-auto fa fa-arrow-up"></i>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                </div>
            </div>
        </div>

        {% block content %}

        {% endblock %}
    </div>
</div>
{{ room.id|json_script:"room-name" }}
{{ request.user.username|json_script:"user" }}

<script src="{% static 'js/reconnecting-websocket.js' %}"></script>
{% block js %}

{% endblock %}
</body>
</html>

templates/layout/cdn.html
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script type='text/javascript'
        src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js'></script>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
      crossorigin="anonymous" referrerpolicy="no-referrer"/>


<!-- JavaScript -->
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>

<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
<!-- Default theme -->
{#<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>#}
<!-- Semantic UI theme -->
{#    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/semantic.min.css"/>#}
<!-- Bootstrap theme -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/bootstrap.min.css"/>